apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-microservice
  template:
    metadata:
      labels:
        app: fastapi-microservice
  spec:
      containers:
      - name: fastapi-microservice
        image: sarfo97/fastapi-microservice:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-microservice-service
spec:
  type: LoadBalancer
  selector:
    app: fastapi-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
