apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-microservice
  template:
    metadata:
      labels:
        app: fastapi-microservice
    spec:  
      containers:
        - name: fastapi-microservice
          image: us-central1-docker.pkg.dev/fastai/fastapi-k8s:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-microservice-service
spec:
  type: LoadBalancer
  selector:
    app: fastapi-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
