name: DEV - Deploy to GCP Kubernetes

on:
  push:
    branches:
      - master

env:
  GCP_PROJECT_ID: constant-tracer-434122-q2
  GKE_CLUSTER: autopilot-cluster-1
  GKE_REGION: us-central1
  IMAGE_NAME: sarfo97/fastapi-k8s  # Replace with your Docker Hub username and image name
  IMAGE_TAG: latest


jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_REGION }}

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/your-deployment-name \
          your-container-name=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
